[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = [
  ".venv",
  "install",
  "static",
  "templates",
  "scripts",
]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B", "SIM"]
extend-select = ["C90"]  # optional: flake8-comprehensions
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.isort]
profile = "black"
line_length = 100

[tool.black]
line-length = 100
target-version = ["py311"]
