[tool.ruff]
line-length = 100
target-version = "py311"
extend-select = ["C90"]  # optional: flake8-comprehensions
ignore = []

[tool.ruff.lint]
select = ["E","F","W","I","UP","B","SIM"]
# E,F,W - pycodestyle/pyflakes, I - isort, UP - pyupgrade, B - bugbear, SIM - simplify

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.isort]
profile = "black"
line_length = 100

[tool.black]
line-length = 100
target-version = ["py311"]
