version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./install/docker/.env.db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: .
      dockerfile: install/docker/Dockerfile
    env_file:
      - ./install/docker/.env
      - ./install/docker/.env.db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    ports:
      - "8010:8010"
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  pgdata:
